root = "."
tmp_dir = "tmp"

[build]
  bin = "./dice-server"
  cmd = "go build -o ./dice-server"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "GO_ENV=development ./dice-server"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "yaml", "env"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = constants.EmptyStr
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
