name: dice-test-suite
on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "**.txt"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "LICENSE"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"
      - "docs/**"
      - ".github/**"
      - "**.txt"
      - "**.json"
      - "**.yaml"
      - "**.yml"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"
      - name: Cache dependencies
        uses: actions/cache@v3
        with: # Cache the Go modules
          path: |
            vendor/
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: dorny/paths-filter@v3
        id: file_types
        with:
          filters: |
            watch_file_changes:
              - '**/*.go'
      - name: Install dependencies
        run: go get -v . # Check if there is any version changes from the cache
      - name: Run Unit tests
        if: steps.file_types.outputs.watch_file_changes == 'true'
        run: make unittest
      - name: Run Integration tests
        if: steps.file_types.outputs.watch_file_changes == 'true'
        run: make test
